apiVersion: batch/v1
kind: Job
metadata:
  name: eks-iam-test-s3
  namespace: team-riker
spec:
  template:
    metadata:
      labels:
        app: eks-iam-test-s3
    spec:
      serviceAccountName: irsa-demo
      containers:
      - name: eks-iam-test
        image: amazon/aws-cli:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["s3", "ls"]
      restartPolicy: Never
