spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/CloudQuest-LLC/eks-blueprints-workloads
    targetRevision: main
  ingress:
    host: dev.example.com